### ISSUE TITLE
Where can I see the demo video？

### ISSUE THREAD

**Issue by cgrrty** [Ezward/Esp32CameraRover2#2]
Where can I see the demo video

**Comment by Ezward** [comment]
I currently do not have a video of the rover in action.  My current prototype works well, but is very ugly; I'd like to do a second build that looks better before I post a video.  I was hoping to get autonomous path following working before I made the project really public, but I may do that sooner.  At this point (tag v0.7) I have pretty good speed control and pose estimation working.  I also have telemetry being plotted in realtime.  So I think I need to do at least two videos at first; 1) How to build the rover 2) How to calibrate and operate it using the web ui.

**Comment by cgrrty** [comment]
Hi
I am a hardware engineer. I want to join in and design pcb for this project
thanks

**Comment by Ezward** [comment]
Hi @cgrrty That is exciting.  I've added a slapdash wiring diagram to the documentation; you can look at that.  I'll also post a few pictures of the prototype; it's a lot of cardboard and tape so I've avoided posting photos, but they are probably worth posting if you want to see how this thing works.  This weekend I will also post a short video of the go-to-goal behavior in action.  You will see in the photos that the ESP32 cam is mounted up on a 'stand' currently made of cardboard and foamboard.  If you are going to design a PCB for this, it would be really cool to have a board that also serves as the 'stalk' for the camera; so a long-ish PCB that could be stood on it's end so the camera is up high.  We could design a 3d printed base that the PCB could be inserted into to hold it at a good angle for the camera to see in front of it.

**Comment by cgrrty** [comment]
Hi Ezward 
Can you publish videos on bilibili ([](https://www.bilibili.com/))at the same time? I think more people will see and be interested in this way

**Comment by Ezward** [comment]
@cgrrty I've added video links to the documentation.  So for there are 3 videos; 

EzRover Introduction, https://youtu.be/yN2ya2mlBNU
EzRover Calibration, https://youtu.be/ciDCUUx8MXI
EzRover Go to Goal Behavior, https://youtu.be/_eKCqswX5D0

I'll look at getting these up on bilibili.

There is also a slideshow (under construction) that describes the algorithms used in EzRover; https://docs.google.com/presentation/d/1t77gDPORG4qcxwhPNWrPlTVjwQWncRw7ujsnF02ZN7E/edit?usp=sharing

Future videos will be on
- Gamepad connection and control
- A video showing the rover in operation
- discussion of C++ internals and extension points
- discussion of JavaScript internals and extension points

**Comment by Ezward** [comment]
@cgrrty Here is a video showing the robot in action; https://youtu.be/TjE9ceNOTJE

**Comment by cgrrty** [comment]
Very good video, if posted on bilibili, more people will watch it. 
I'm sure they'll be interested, too.
Very good video, if posted on bilibili, more people will watch it. I'm sure they'll be interested, too.
If the language is a problem for you, I can post it on your behalf.

**Comment by cgrrty** [comment]
Science and technology video like this
[https://www.bilibili.com/video/BV1UE411P7hx?from=search&seid=16049779974724068010]()

**Comment by Ezward** [comment]
I could probably figure out how to sign up and post a video on bilibili using google translate, but I could not provide a good description.  I doubt google will do a good job translating.

**Comment by cgrrty** [comment]
Hi
I will upload the video to bilibili sometime, which may take some time.
There is no problem with the overview you wrote in Chinese.
Later, I will buy materials to build the prototype first.
After that, I will design the schematic first, and then I will draw the PCB after you review it.
By the way, what software do you usually use to design PCB and schematics on your side?

**Comment by Ezward** [comment]
@cgrrty I'm a software guy; I've not designed a PCB before.  So something open source that would run on Linux; maybe KiCad.  I can provide input on physical form factor that would work well for the robot.  I also have a number of ideas about how to improve the robot's hardware.  Some of those are discussed in the docs.  Specifically, I want to create a version of the robot that use a PCA9685 module to control the motors; that will free up some pins.  With those pins we can re-enable serial port or we can support quadrature encoder motors.  So we would connect to the PCA9685 over I2C, the use it to drive the motor's PWM duty cycle.  We could then also add other I2C devices to that bus, like an OLED display.  I don't think we need to put the PCA9685 functionality on the board, we just need to make sure the I2C pins on the ESP32Cam are available so we can add an external module.
