### ISSUE TITLE
About network issues

### ISSUE THREAD

**Issue by cgrrty** [Ezward/Esp32CameraRover2#5]
Hi
I have two questions，about wireless networks
1、Whether the device can use a fixed ip to quickly link the device？
2、Can automatically reconnect after network failure？
Thanks

**Comment by Ezward** [comment]
1. Current code simply connects to the wifi indicated in wifi_credentials.h.  You can use your wifi router's admin to choose an ip for the rover.  This is often called IP Address Reservation in that admin ui.  I could add a mode where the rover servers as an access point; then the computer of phone would connect to it.  If that sounds like what you are asking, let me know (or add a feature request in issues!).
2. The rover will try to reconnect after a failure, but I have found it to be unreliable.  There is some work to do there.  I probably need to do a more thorough reload of the client, as if the page was reloaded.

**Comment by cgrrty** [comment]
HI
   The rover can be set as an access point but it is not necessary.
Setting the rover  as  an access point will cause the mobile phone or computer  cannot be accessed Internet  normally when they are connect to the  rover’s network,
thanks

**Comment by cgrrty** [comment]
HI
   The rover can be set as an access point but it is not necessary.
Setting the rover  as  an access point will cause the mobile phone or computer  cannot be accessed Internet  normally when they are connect to the  rover’s network,
thanks

**Comment by Ezward** [comment]
Did this answer your question?
