### ISSUE TITLE
I did measure the latency

### ISSUE THREAD

**Issue by cgrrty** [Ezward/Esp32CameraRover2#8]
![20210214204720](https://user-images.githubusercontent.com/14201584/107877191-dc82a080-6f05-11eb-91e7-4949134ad7f2.png)
Can we learn something from this project? [https://github.com/OpenHD/Open.HD/wiki](url)

**Comment by cgrrty** [comment]
The picture is instantaneous, and sometimes the  latency is more serious.

**Comment by Ezward** [comment]
I'll take a look.

**Comment by Ezward** [comment]
They mention a best case latency of 40 to 50ms, which is pretty good.   It looks like what they are doing is using low level access to the wifi chips in some usb wifi adapters to create a lower latency protocol.

**Comment by Ezward** [comment]
I'm going to close this issue and we can track the other two issues that came out of this.  Thanks.
